### ISSUE TITLE
Extra Frequency Channel in output array

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#12]
When simulating the full GLEAM directory provided by default, the returned frequency array has a duplicated frequency. This causes an error during write out with pyuvdata, along with being generally undesirable since the number of frequencies returned was different than the output parameters. Original output for this simulation had 1024 frequency channels

![image](https://cloud.githubusercontent.com/assets/8646829/24677612/38df18fa-193c-11e7-9c47-b197b1cfe13a.png)

**Comment by nithyanandan** [comment]
Fixed in 3efb300
