### ISSUE TITLE
paper_dipole not supported

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#2]
under telescope, id the 'paper_dipole' option is listed as an accepted parameter. however run_prisim.py  has no defaults configuration settings for 'paper_dipole' near line 355. While all necessary parameters can be set manually it would be nice to either have this option supported or removed.

**Comment by nithyanandan** [comment]
Could you provide as much info as possible on the PAPER dipole? What is its effective length, height above the ground plane, etc.? I can edit defaults to support this option.

**Comment by mkolopanis** [comment]
These are the parameters I have been using to simulate the paper dipoles:

A_eff: 4 

Trx: 200
Tant_ref: 180
Tsys: 280

size: 2
orientation: [90,270]
ocords: altaz
ground_plane: .5

All these parameters may not be explicitly correct but they are producing sufficient results at least

**Comment by nithyanandan** [comment]
- Feature addition commenced on 'PAPER' branch from 'master' at 6efc096
- PAPER-64 and PAPER-128 layouts added in b389537 of 'PAPER' branch
- Allow options to set telescope id parameter in config YAML file to 'paper' in 4821cde of 'PAPER' branch. This was previously denoted by 'paper_dipole'
- Setting telescope id to 'paper' only predetermines element shape ('dipole') and size (2.0 m). The other parameters describing the antenna element still have to be specified explicitly like ground plane height, effective area, element orientation, antenna and receiver temperatures, etc. Other values have not been preset to provide more flexibility and ability to customize and also such additional presets must be provided for other telescope ids as well which isn't the case at the moment.
- Merged branch 'PAPER' with 'master' at 4821cde
- Needs verification if feature addition functions accurately

**Comment by nithyanandan** [comment]
Assumed that PAPER-128 layout is (16 x 30m EW) x (8 x 4m NS) but could be wrong and needs confirmation.

**Comment by nithyanandan** [comment]
* Change PAPER-128 to PAPER-112 in branch 'PAPER' at 6d245f2
* PAPER-112 layout updated to (16 x 15m EW) x (7 x 4m NS) after verifying with Jonnie Pober and Danny Jacobs
* Merged branch 'PAPER' with 'master' at 6d245f2
