### ISSUE TITLE
Phasing in make redundant visibilities

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#24]
In the interest of efficiency the phasing of the visibilities in make_redundant_visibilities should occur before duplicate_measurements is called. This is necessary if writing to uvfits files, but not inherently necessary for the hdf5 output format.

**Comment by nithyanandan** [comment]
This was an issue in commit 7c44eb3

**Comment by nithyanandan** [comment]
Fixed in commit 94f15d0 
Needs testing.

**Comment by nithyanandan** [comment]
Closed until further issues found.
