### ISSUE TITLE
pyuvdata dependence paradox

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#27]
the setup.py file requires specifically pyuvdata==1.1:
https://github.com/nithyanandan/PRISim/blob/4431f336a52d31f4b2a0e0599bcd2626550721f8/setup.py#L51-L60

however pyuvdata had no UVBeam object until [v1.2](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/tree/v1.2). Should this just by pyuvdata>=1.1 (or 1.2 for uvbeam and external beam support) or is there a specific reason to link to this tag?

**Comment by nithyanandan** [comment]
No reason to not update. Updated in a147da6bb786f9f645c2152155de5e834420c456. Found to work with pyuvdata 1.3
