### ISSUE TITLE
GEOM.altaz2hadec() is passed incorrect shape

### ISSUE THREAD

**Issue by jackson-sipple** [nithyanandan/PRISim#34]
`GEOM.altaz2hadec(altaz, lattitude, units)` requires the parameter `altaz` to be "a list of tuples or Nx2 Numpy array" yet `altaz=self.pointing_center[-1,:]` is a 1-D numpy array. This leads to an IndexError when the function is called.

https://github.com/nithyanandan/PRISim/blob/a3b9a254f45703607f85ee00fd139637c2ce10be/prisim/interferometry.py#L6042

**Comment by nithyanandan** [comment]
Could you please post the full traceback? Also, what is the git hash of the AstroUtils package you are using? Also, please provide the input YAML file that you ran PRISim with so as to understand your use case that goes through that part of the code.

**Comment by nithyanandan** [comment]
Regardless of the code path, I've tried to guard against shape incompatibilities based on changes in AstroUtils (a50eeb6618402442336f48d152e6a8adb18c94ae) and PRISim (8061bbda7e636b41ab288712f89e05c2bec0ea60). 

Can you confirm that this fixes the issue?
