### ISSUE TITLE
input parameters from the power spectrum example are giving error

### ISSUE THREAD

**Issue by matikasiyanda** [nithyanandan/PRISim#36]
https://github.com/nithyanandan/PRISim/blob/234d16748a00b1ff1a7d04e69c1380ae28b725de/prisim/bispectrum_phase.py#L3178

When I use the following params;
autoinfo = {'axes': 2, 'wts': None}
xinfo = {'axes': None, 'avgcov': False, 'collapse_axes': [], 
                 'wts':{'preX': None, 'preXnorm': False, 
                        'postX': None, 'postXnorm': False}}
and attempt to compute the power spectrum,
EE_=R.compute_power_spectrum(autoinfo=autoinfo,xinfo=xinfo,beamparms=beam_stuff)

TypeErrorTraceback (most recent call last)
<ipython-input-22-0353368ac0a6> in <module>()
----> 1 EE_=R.compute_power_spectrum(autoinfo=autoinfo,xinfo=xinfo,beamparms=beam_stuff)#selection=select_f

/lustre/aoc/projects/hera/smatika/u/envs/PRISM_Simulation/lib/python2.7/site-packages/prisim/bispectrum_phase_.py in compute_power_spectrum(self, cpds, selection, autoinfo, xinfo, cosmo, units, beamparms)
   3270             if autoinfo['axes'] is not None:
   3271                 if not isinstance(autoinfo['wts'], list):
-> 3272                     raise TypeError('wts in input autoinfo must be a list of numpy arrays')
   3273                 else:
   3274                     if len(autoinfo['wts']) != len(autoinfo['axes']):

TypeError: wts in input autoinfo must be a list of numpy arrays

**Comment by nithyanandan** [comment]
The codes have evolved a long way since. Did you try using the Jupyter notebook examples I gave you? Can you confirm if this is still the case?

**Comment by nithyanandan** [comment]
Not heard anything. Assuming fixed.
