### ISSUE TITLE
Feature Request, specify foreground filepath 

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#4]
It would be convenient to be able to specify the foreground (or pfb, antenna location, phase info, etc) custom file path as an individual parameter. 

i.e.
catalog:

     filepathtype: 'custom'

     custom_path: '/path/to/foregrounds'
 
     SUMSS_File= 'sumss_catalog.txt'

**Comment by nithyanandan** [comment]
This feature has been available for a while, at least since 1d5505c
