### ISSUE TITLE
uvdata default pointing

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#8]
It would be nice to have an option for the phase_center parameter where the user can specify the "time" of the scan. For example having an option to phase to the start of the scan, middle of scan, or end of scan as well as being able to specify exact ra/dec if desired.

**Comment by nithyanandan** [comment]
Can now accommodate default option in phase_center parameter (by setting to null) under 'Save Format' in defaultparms.yaml

Fixed in 'phasing' branch and merged onto master at 1edd7a9
