### ISSUE TITLE
Manually specify flux cut

### ISSUE THREAD

**Issue by mkolopanis** [nithyanandan/PRISim#9]
Manually setting the flux cut level for source catalogs would be a nice addition for users running only compact catalogs.

**Comment by nithyanandan** [comment]
Ticket created on master branch 6d245f2

**Comment by nithyanandan** [comment]
Feature added in branch flux-cut through use of parameters flux_min, flux_max, and fluxcut_reffreq in defaultparms.yaml

Branch flux-cut merged into branch master at 6c2896d
